default: &default
  adapter: postgresql
  encoding: unicode
  port: 5432
  host: <%= ENV["POSTGRES_HOST"] %>
  username: postgres
  password: postgres
development:
  <<: *default
  database: api_spellbook_exemplo_development
test:
  <<: *default
  database: api_spellbook_exemplo_test
production:
  pool: 5
timeout: 5000
